# Generated by Django 4.2.7 on 2025-07-25 01:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecognitionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('success', 'Successful Recognition'), ('failed', 'Failed Recognition'), ('multiple', 'Multiple Faces Detected'), ('no_face', 'No Face Detected'), ('low_quality', 'Low Quality Image'), ('unknown', 'Unknown Person')], max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('image_hash', models.CharField(blank=True, help_text='SHA256 hash of the image', max_length=64)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('face_count', models.IntegerField(default=0)),
                ('matched_encoding_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Recognition Log',
                'verbose_name_plural': 'Face Recognition Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='face_recogn_user_id_a8fe41_idx'), models.Index(fields=['result', 'timestamp'], name='face_recogn_result_3ba189_idx'), models.Index(fields=['timestamp'], name='face_recogn_timesta_f73d10_idx')],
            },
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encoding_data', models.TextField(help_text='JSON serialized face encoding array')),
                ('confidence_score', models.FloatField(help_text='Confidence score of the face encoding', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.CharField(choices=[('enrollment', 'Initial Enrollment'), ('update', 'Profile Update'), ('retrain', 'Model Retrain')], default='enrollment', max_length=20)),
                ('image_path', models.CharField(blank=True, help_text='Path to the source image', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary encoding for recognition')),
                ('face_location', models.TextField(blank=True, help_text='JSON serialized face location coordinates')),
                ('image_quality_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_encodings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Encoding',
                'verbose_name_plural': 'Face Encodings',
                'ordering': ['-is_primary', '-confidence_score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='face_recogn_user_id_9f3ec1_idx'), models.Index(fields=['is_primary', 'is_active'], name='face_recogn_is_prim_17a27e_idx')],
            },
        ),
    ]
