# Generated by Django 4.2.7 on 2025-07-25 01:52

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('break_start_time', models.DateTimeField(blank=True, null=True)),
                ('break_end_time', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.DurationField(blank=True, null=True)),
                ('break_duration', models.DurationField(blank=True, null=True)),
                ('overtime_hours', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('on_leave', 'On Leave')], default='present', max_length=20)),
                ('recognition_method', models.CharField(choices=[('face', 'Face Recognition'), ('manual', 'Manual Entry'), ('card', 'ID Card'), ('mobile', 'Mobile App')], default='face', max_length=20)),
                ('recognition_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('face_encoding_used', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', '-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('standard_work_start', models.TimeField(default=datetime.time(9, 0))),
                ('standard_work_end', models.TimeField(default=datetime.time(17, 0))),
                ('late_threshold_minutes', models.IntegerField(default=15)),
                ('standard_break_duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('max_break_duration', models.DurationField(default=datetime.timedelta(seconds=7200))),
                ('overtime_threshold_hours', models.FloatField(default=8.0)),
                ('overtime_rate_multiplier', models.FloatField(default=1.5)),
                ('min_recognition_confidence', models.FloatField(default=0.6)),
                ('allow_manual_override', models.BooleanField(default=True)),
                ('require_admin_approval', models.BooleanField(default=False)),
                ('send_late_notifications', models.BooleanField(default=True)),
                ('send_absence_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Attendance Settings',
                'verbose_name_plural': 'Attendance Settings',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('sick', 'Sick Leave'), ('vacation', 'Vacation'), ('personal', 'Personal Leave'), ('emergency', 'Emergency Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_half_day', models.BooleanField(default=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
